# This file contains the values that will usually need to be updated when changing versions of Garden Linux or NVIDIA driver

# The pull secret config will likely need to be set only once for a given deployment

# TODO: List of pre-existing secrets containing private registry credentials
# For example
# imagePullSecrets:
# - name: myRegistryKeySecretName
imagePullSecrets:
- name: ghcr-login-secret

# Configure a secret that should be created and then used for pulling images
imagePullSecret:
  # TODO: decide whether you want to create a new secret or use an existing one (using imagePullSecrets above)
  enabled: false
  # TODO: change e30k to a base64-encoded Docker registry JSON authentication file
  dockercfg: "e30K"
  annotations:

nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["g6.xlarge", "g5.xlarge"]

nvidiaInstaller:
  # TODO: set your registry host/path if using a non-"docker.io" registry, otherwise leave empty
  imageRegistry: "ghcr.io/pbochynski"
  # TODO: Set to the name of the image in the Docker registry
  installerImage: gardenlinux-nvidia-installer
  # TODO: Edit image tag
  installerTag: 560.35.03

nvidiaDevicePlugin:
  # TODO: Edit <driver-version>
  nvidiaDriverVersion: 560.35.03

debug: true